name: Build and deploy static HTML app to Azure Web App - new-training-web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: html-app
          path: .

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'new-training-web-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
