# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Simplified workflow for pure HTML app

name: Deploy static HTML app to Azure Web App - new-training-web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Login to Azure using Service Principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      # 3️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'new-training-web-app'
          slot-name: 'Production' # remove this line if you don't use deployment slots
          package: .
